version: '2'
services:
  proxy:
    container_name: privoxy-i2p-tor
    build:
      context: .
    restart: unless-stopped
    ports:
      - 8118:8118/tcp
      - 4444:4444/tcp
      - 9050:9050/tcp
