name: Publish Docker Image

on:
  schedule:
    - cron: '20 5 * * *'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.git*'
      - 'docker-compose.yml'
  push:
    branches:
      - main
    paths-ignore:
      - '.git*'
      - 'docker-compose.yml'
  workflow_dispatch:

env:
  IMAGE_BASE: library/alpine:latest
  REPO_NAME: ${{ github.event.repository.name }}
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:

  variables:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.split.outputs.image_name }}
    steps:
      - name: Set name of image
        id: split
        run: echo "image_name=${REPO_NAME#*-}" >> $GITHUB_OUTPUT

  check:
    needs: variables
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ needs.variables.outputs.image_name }}
    outputs:
      image-needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1.2.0
        with:
          base-image: ${{ env.IMAGE_BASE }}
          image: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        if: github.event_name == 'schedule'

  build:

    needs: [check, variables]

    env:
      IMAGE_NAME: ${{ needs.variables.outputs.image_name }}

    if: |
      github.event_name != 'schedule' ||
      needs.check.outputs.image-needs-updating == 'true'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Docker Hub registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        if: github.event_name != 'pull_request'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.base.name=docker.io/${{ env.IMAGE_BASE }}
          tags: |
            type=sha
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract Docker PR tag
        if: github.event_name == 'pull_request'
        id: meta_pr
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.base.name=docker.io/${{ env.IMAGE_BASE }}
          tags: |
            type=sha
            type=ref,event=pr

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.IMAGE_BASE }}
          platforms: linux/386, linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
