name: Update README

on:
  push:
    branches:
      - main
    paths:
      - 'README.*'
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REGISTRY_URL: docker.io
  REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:

  variables:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.split.outputs.image_name }}
    steps:
      - name: Set name of image
        id: split
        run: echo "image_name=${REPO_NAME#*-}" >> $GITHUB_OUTPUT

  update:

    needs: variables
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ needs.variables.outputs.image_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
          repository: ${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
